language: java
sudo: false
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
deploy:
  provider: heroku
  app: thawing-reef-71512
  api_key: f31258e3-e6b5-440e-bde8-bd374fc5531c
after_success:
  - mvn clean cobertura:cobertura
  - java -jar ~/codacy-coverage-reporter-assembly.jar report -l Java -r target/site/cobertura/coverage.xml
